Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2024
Var
// Seção de Declarações das variáveis 
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu nome: ")
   leia (nome)
   escreval ("Muito prazer, ", nome)

Fimalgoritmo